// <auto-generated />
using System;
using HealthLogger.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HealthLogger.Migrations
{
    [DbContext(typeof(HealthLoggerDbContext))]
    [Migration("20260807053854_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HealthLogger.Entities.BodyMetricEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DiastolicBP")
                        .HasColumnType("int");

                    b.Property<DateOnly>("MeasurementDate")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SystolicBP")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("WaistCircumferenceCm")
                        .HasColumnType("float");

                    b.Property<double?>("WeightKg")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "MeasurementDate");

                    b.ToTable("BodyMetrics", (string)null);
                });

            modelBuilder.Entity("HealthLogger.Entities.CustomRecipeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double?>("CustomCalories")
                        .HasColumnType("float");

                    b.Property<double?>("CustomCaloriesKj")
                        .HasColumnType("float");

                    b.Property<double?>("CustomCarbohydrate")
                        .HasColumnType("float");

                    b.Property<double?>("CustomFat")
                        .HasColumnType("float");

                    b.Property<double?>("CustomProtein")
                        .HasColumnType("float");

                    b.Property<double?>("CustomSalt")
                        .HasColumnType("float");

                    b.Property<double?>("CustomSaturatedFat")
                        .HasColumnType("float");

                    b.Property<double?>("CustomSugar")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NutritionMode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("ProductWeightG")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CustomRecipes", (string)null);
                });

            modelBuilder.Entity("HealthLogger.Entities.DailyCheckinEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("AlcoholUnits")
                        .HasColumnType("float");

                    b.Property<DateOnly>("CheckinDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EnergyLevel")
                        .HasColumnType("int");

                    b.Property<bool?>("ExerciseDone")
                        .HasColumnType("bit");

                    b.Property<string>("ExerciseType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MoodRating")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("SleepHours")
                        .HasColumnType("float");

                    b.Property<int?>("SleepQuality")
                        .HasColumnType("int");

                    b.Property<int?>("StepCount")
                        .HasColumnType("int");

                    b.Property<int?>("StressLevel")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("WaterIntakeLiters")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CheckinDate")
                        .IsUnique();

                    b.ToTable("DailyCheckins", (string)null);
                });

            modelBuilder.Entity("HealthLogger.Entities.FoodEntryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("date");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TotalCalories")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "EntryDate");

                    b.ToTable("FoodEntries", (string)null);
                });

            modelBuilder.Entity("HealthLogger.Entities.FoodEntryItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double?>("CustomCalories")
                        .HasColumnType("float");

                    b.Property<Guid>("FoodEntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FoodItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PortionGrams")
                        .HasColumnType("float");

                    b.Property<Guid?>("RecipeInstanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SourceRecipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceRecipeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FoodEntryId");

                    b.HasIndex("FoodItemId");

                    b.ToTable("FoodEntryItems", (string)null);
                });

            modelBuilder.Entity("HealthLogger.Entities.FoodItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Barcode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BarcodeSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Carbohydrate")
                        .HasColumnType("float");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("EnergyKcal")
                        .HasColumnType("float");

                    b.Property<double>("EnergyKj")
                        .HasColumnType("float");

                    b.Property<double>("Fat")
                        .HasColumnType("float");

                    b.Property<double?>("Fiber")
                        .HasColumnType("float");

                    b.Property<int?>("FineliId")
                        .HasColumnType("int");

                    b.Property<bool>("IsUserCreated")
                        .HasColumnType("bit");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NameFi")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NameSv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Protein")
                        .HasColumnType("float");

                    b.Property<double?>("Salt")
                        .HasColumnType("float");

                    b.Property<double?>("SaturatedFat")
                        .HasColumnType("float");

                    b.Property<double?>("Sugar")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("FineliId");

                    b.HasIndex("NameEn");

                    b.HasIndex("NameFi");

                    b.HasIndex("UserId", "Barcode")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL AND [Barcode] IS NOT NULL");

                    b.ToTable("FoodItems", (string)null);
                });

            modelBuilder.Entity("HealthLogger.Entities.FoodPhotoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AiAnalysisJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AnalyzedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("FoodEntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IdentifiedItems")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FoodEntryId");

                    b.HasIndex("UserId");

                    b.ToTable("FoodPhotos", (string)null);
                });

            modelBuilder.Entity("HealthLogger.Entities.RecipeIngredientEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FoodItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<double>("PortionGrams")
                        .HasColumnType("float");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FoodItemId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeIngredients", (string)null);
                });

            modelBuilder.Entity("HealthLogger.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("HealthLogger.Entities.UserPreferencesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DailyCalorieTarget")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefaultMealTypes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EnableNotifications")
                        .HasColumnType("bit");

                    b.Property<double?>("HeightCm")
                        .HasColumnType("float");

                    b.Property<bool>("InboundIntegrationEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("InboundIntegrationKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OutboundIntegrationEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("OutboundIntegrationUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReminderTimes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("TargetWaistCm")
                        .HasColumnType("float");

                    b.Property<double?>("TargetWeightKg")
                        .HasColumnType("float");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitSystem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserPreferences", (string)null);
                });

            modelBuilder.Entity("HealthLogger.Entities.BodyMetricEntity", b =>
                {
                    b.HasOne("HealthLogger.Entities.UserEntity", "User")
                        .WithMany("BodyMetrics")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthLogger.Entities.CustomRecipeEntity", b =>
                {
                    b.HasOne("HealthLogger.Entities.UserEntity", "User")
                        .WithMany("CustomRecipes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthLogger.Entities.DailyCheckinEntity", b =>
                {
                    b.HasOne("HealthLogger.Entities.UserEntity", "User")
                        .WithMany("DailyCheckins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthLogger.Entities.FoodEntryEntity", b =>
                {
                    b.HasOne("HealthLogger.Entities.UserEntity", "User")
                        .WithMany("FoodEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthLogger.Entities.FoodEntryItemEntity", b =>
                {
                    b.HasOne("HealthLogger.Entities.FoodEntryEntity", "FoodEntry")
                        .WithMany("Items")
                        .HasForeignKey("FoodEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthLogger.Entities.FoodItemEntity", "FoodItem")
                        .WithMany("EntryItems")
                        .HasForeignKey("FoodItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FoodEntry");

                    b.Navigation("FoodItem");
                });

            modelBuilder.Entity("HealthLogger.Entities.FoodItemEntity", b =>
                {
                    b.HasOne("HealthLogger.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthLogger.Entities.FoodPhotoEntity", b =>
                {
                    b.HasOne("HealthLogger.Entities.FoodEntryEntity", "FoodEntry")
                        .WithMany("Photos")
                        .HasForeignKey("FoodEntryId");

                    b.HasOne("HealthLogger.Entities.UserEntity", "User")
                        .WithMany("FoodPhotos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodEntry");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthLogger.Entities.RecipeIngredientEntity", b =>
                {
                    b.HasOne("HealthLogger.Entities.FoodItemEntity", "FoodItem")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("FoodItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthLogger.Entities.CustomRecipeEntity", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodItem");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("HealthLogger.Entities.UserPreferencesEntity", b =>
                {
                    b.HasOne("HealthLogger.Entities.UserEntity", "User")
                        .WithOne("Preferences")
                        .HasForeignKey("HealthLogger.Entities.UserPreferencesEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthLogger.Entities.CustomRecipeEntity", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("HealthLogger.Entities.FoodEntryEntity", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Photos");
                });

            modelBuilder.Entity("HealthLogger.Entities.FoodItemEntity", b =>
                {
                    b.Navigation("EntryItems");

                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("HealthLogger.Entities.UserEntity", b =>
                {
                    b.Navigation("BodyMetrics");

                    b.Navigation("CustomRecipes");

                    b.Navigation("DailyCheckins");

                    b.Navigation("FoodEntries");

                    b.Navigation("FoodPhotos");

                    b.Navigation("Preferences");
                });
#pragma warning restore 612, 618
        }
    }
}
